title: Lukasz Dev Blog
email: lukasz@lukaszcaputa.eu
description: >- # this means to ignore newlines until "baseurl:"
  Lukasz DEV blog
baseurl: ""
url: "https://LukaszCaputa.github.io"
github_username:  LukaszCaputa
linkedin_username: lukasz-caputa

# Build settings
theme: minima
plugins:
  - jekyll-feed

