title: Lukasz Caputa Tech Blog
email: lukasz@lukaszcaputa.eu
description: >- # this means to ignore newlines until "baseurl:"
  Lukasz Caputa Tech Blog
baseurl: ""
url: "https://LukaszCaputa.github.io"
github_username:  LukaszCaputa
linkedin_username: Lukasz-Caputa

# Build settings
theme: minima
plugins:
  - jekyll-feed

